trigger:
- new

pool: default

steps:
- script: ls -ltr
  displayName: 'List files in the working directory'

- task: SonarQubePrepare@6
  inputs:
    SonarQube: 'sonar'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'cicds'
    cliProjectName: 'cicd'
    cliSources: 'testapp'
- task: SonarQubeAnalyze@6
  inputs:
    jdkversion: 'JAVA_HOME_17_X64'

