trigger:
- new

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: ls -ltr
  displayName: 'List files in the working directory'

- task: Docker@2
  inputs:
    containerRegistry: 'dockerhub'
    repository: 'akshayasgo/nodetest'
    command: 'buildAndPush'
    Dockerfile: 'testapp/Dockerfile'
    buildContext: 'testapp'
    tags: '$(Build.BuildId)'  # Use the build ID as the tag
  displayName: 'Build and Push Docker Image'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'webapp'
    appType: 'webAppContainer'
    WebAppName: 'kahsyate'
    DockerNamespace: 'docker.io'
    DockerRepository: 'akshayasgo/nodetest'
    DockerImageTag: '$(Build.BuildId)'
  displayName: 'Deploy to Azure Web App'