trigger:
  - none

pool:
  default

steps:
- script: ls -ltr
  displayName: 'List files in the working directory'

- task: SonarQubePrepare@6
  inputs:
    SonarQube: 'sonar'
    scannerMode: 'CLI'
    configMode: 'project'  # Set configMode to 'project' to use the project-level configuration
    cliProjectKey: 'cicd1'
    cliProjectName: 'cicd1'
    cliSources: 'testapp'

- task: SonarQubeAnalyze@6
  inputs:
    jdkversion: 'JAVA_HOME_17_X64'