# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- new

pool: default

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line '

- task: Docker@2
  inputs:
    containerRegistry: 'dockerhub'
    repository: 'akshayasgo/nodetest'
    command: 'buildAndPush'
    Dockerfile: 'testapp/Dockerfile'